cat_list = [['astro-ph', 'Astrophysics', '宇宙物理学'],
 ['astro-ph.CO', 'Cosmology and Nongalactic Astrophysics', '宇宙論と非銀河宇宙物理学'],
 ['astro-ph.EP', 'Earth and Planetary Astrophysics', '地球惑星天体物理学'],
 ['astro-ph.GA', 'Astrophysics of Galaxies', '銀河の天体物理学'],
 ['astro-ph.HE', 'High Energy Astrophysical Phenomena', '高エネルギー天体物理現象'],
 ['astro-ph.IM',
  'Instrumentation and Methods for Astrophysics',
  '天体物理学のための装置と方法'],
 ['astro-ph.SR', 'Solar and Stellar Astrophysics', '太陽・恒星天体物理学'],
 ['cond-mat.dis-nn',
  'Disordered Systems and Neural Networks',
  '乱れたシステムとニューラルネットワーク'],
 ['cond-mat.mes-hall', 'Mesoscale and Nanoscale Physics', 'メソスケール・ナノスケール物理学'],
 ['cond-mat.mtrl-sci', 'Materials Science', '材料科学'],
 ['cond-mat.other', 'Other Condensed Matter', 'その他の凝縮物'],
 ['cond-mat.quant-gas', 'Quantum Gases', '量子気体'],
 ['cond-mat.soft', 'Soft Condensed Matter', '軟質凝縮物'],
 ['cond-mat.stat-mech', 'Statistical Mechanics', '統計力学'],
 ['cond-mat.str-el', 'Strongly Correlated Electrons', '強相関電子'],
 ['cond-mat.supr-con', 'Superconductivity', '超電導'],
 ['cs.AI', 'Artificial Intelligence', '人工知能'],
 ['cs.AR', 'Hardware Architecture', 'ハードウェアアーキテクチャ'],
 ['cs.CC', 'Computational Complexity', '計算複雑性'],
 ['cs.CE', 'Computational Engineering, Finance, and Science', '計算工学・金融・科学'],
 ['cs.CG', 'Computational Geometry', '計算幾何学'],
 ['cs.CL', 'Computation and Language', '計算と言語'],
 ['cs.CR', 'Cryptography and Security', '暗号とセキュリティ'],
 ['cs.CV', 'Computer Vision and Pattern Recognition', 'コンピュータビジョンとパターン認識'],
 ['cs.CY', 'Computers and Society', 'コンピュータと社会'],
 ['cs.DB', 'Databases', 'データベース'],
 ['cs.DC',
  'Distributed, Parallel, and Cluster Computing',
  '分散、並列、クラスタコンピューティング'],
 ['cs.DL', 'Digital Libraries', 'デジタルライブラリー'],
 ['cs.DM', 'Discrete Mathematics', '離散数学'],
 ['cs.DS', 'Data Structures and Algorithms', 'データ構造とアルゴリズム'],
 ['cs.ET', 'Emerging Technologies', '新技術'],
 ['cs.FL', 'Formal Languages and Automata Theory', '形式言語とオートマトン理論'],
 ['cs.GL', 'General Literature', '一般文学'],
 ['cs.GR', 'Graphics', 'グラフィックス'],
 ['cs.GT', 'Computer Science and Game Theory', '計算機科学とゲーム理論'],
 ['cs.HC', 'Human-Computer Interaction', 'ヒューマンコンピュータインタラクション'],
 ['cs.IR', 'Information Retrieval', '情報検索'],
 ['cs.IT', 'Information Theory', '情報理論'],
 ['cs.LG', 'Learning', '学習'],
 ['cs.LO', 'Logic in Computer Science', 'コンピュータサイエンスの論理'],
 ['cs.MA', 'Multiagent Systems', 'マルチエージェントシステム'],
 ['cs.MM', 'Multimedia', 'マルチメディア'],
 ['cs.MS', 'Mathematical Software', '数理ソフトウェア'],
 ['cs.NA', 'Numerical Analysis', '数値解析'],
 ['cs.NE', 'Neural and Evolutionary Computing', '神経・進化コンピューティング'],
 ['cs.NI', 'Networking and Internet Architecture', 'ネットワーキングとインターネットアーキテクチャ'],
 ['cs.OH', 'Other Computer Science', 'その他のコンピュータサイエンス'],
 ['cs.OS', 'Operating Systems', 'オペレーティングシステム'],
 ['cs.PF', 'Performance', 'パフォーマンス'],
 ['cs.PL', 'Programming Languages', 'プログラミング言語'],
 ['cs.RO', 'Robotics', 'ロボティクス'],
 ['cs.SC', 'Symbolic Computation', '記号計算'],
 ['cs.SD', 'Sound', 'サウンド'],
 ['cs.SE', 'Software Engineering', 'ソフトウェア工学'],
 ['cs.SI', 'Social and Information Networks', '社会・情報ネットワーク'],
 ['cs.SY', 'Systems and Control', 'システムと制御'],
 ['econ.EM', 'Econometrics', '計量経済学'],
 ['eess.AS', 'Audio and Speech Processing', '音声・音声処理'],
 ['eess.IV', 'Image and Video Processing', '画像・映像処理'],
 ['eess.SP', 'Signal Processing', '信号処理'],
 ['gr-qc', 'General Relativity and Quantum Cosmology', '一般相対性理論と量子宇宙論'],
 ['hep-ex', 'High Energy Physics - Experiment', '高エネルギー物理学-実験'],
 ['hep-lat', 'High Energy Physics - Lattice', '高エネルギー物理学 - 格子'],
 ['hep-ph', 'High Energy Physics - Phenomenology', '高エネルギー物理学 - 現象学'],
 ['hep-th', 'High Energy Physics - Theory', '高エネルギー物理学-理論'],
 ['math.AC', 'Commutative Algebra', '可換代数'],
 ['math.AG', 'Algebraic Geometry', '代数幾何学'],
 ['math.AP', 'Analysis of PDEs', 'PDEの分析'],
 ['math.AT', 'Algebraic Topology', '代数トポロジー'],
 ['math.CA', 'Classical Analysis and ODEs', '古典解析とODE'],
 ['math.CO', 'Combinatorics', '組合せ論'],
 ['math.CT', 'Category Theory', 'カテゴリ理論'],
 ['math.CV', 'Complex Variables', '複素変数'],
 ['math.DG', 'Differential Geometry', '微分幾何学'],
 ['math.DS', 'Dynamical Systems', '力学システム'],
 ['math.FA', 'Functional Analysis', '機能解析'],
 ['math.GM', 'General Mathematics', '一般数学'],
 ['math.GN', 'General Topology', '一般的なトポロジー'],
 ['math.GR', 'Group Theory', 'グループ理論'],
 ['math.GT', 'Geometric Topology', '幾何学的トポロジー'],
 ['math.HO', 'History and Overview', '歴史と概要'],
 ['math.IT', 'Information Theory', '情報理論'],
 ['math.KT', 'K-Theory and Homology', 'K理論とホモロジー'],
 ['math.LO', 'Logic', 'ロジック'],
 ['math.MG', 'Metric Geometry', 'メートル幾何学'],
 ['math.MP', 'Mathematical Physics', '数理物理学'],
 ['math.NA', 'Numerical Analysis', '数値解析'],
 ['math.NT', 'Number Theory', '数論'],
 ['math.OA', 'Operator Algebras', 'オペレータ代数'],
 ['math.OC', 'Optimization and Control', '最適化と制御'],
 ['math.PR', 'Probability', '確率'],
 ['math.QA', 'Quantum Algebra', '量子代数'],
 ['math.RA', 'Rings and Algebras', '環と代数'],
 ['math.RT', 'Representation Theory', '表現論'],
 ['math.SG', 'Symplectic Geometry', 'シンプレクティック幾何学'],
 ['math.SP', 'Spectral Theory', 'スペクトル理論'],
 ['math.ST', 'Statistics Theory', '統計理論'],
 ['math-ph', 'Mathematical Physics', '数理物理学'],
 ['nlin.AO', 'Adaptation and Self-Organizing Systems', '適応と自己組織化システム'],
 ['nlin.CD', 'Chaotic Dynamics', 'カオス力学'],
 ['nlin.CG', 'Cellular Automata and Lattice Gases', 'セルオートマトンと格子気体'],
 ['nlin.PS', 'Pattern Formation and Solitons', 'パターン形成とソリトン'],
 ['nlin.SI', 'Exactly Solvable and Integrable Systems', '厳密に解ける系と可積分系'],
 ['nucl-ex', 'Nuclear Experiment', '核実験'],
 ['nucl-th', 'Nuclear Theory', '核理論'],
 ['physics.acc-ph', 'Accelerator Physics', '加速器物理学'],
 ['physics.ao-ph', 'Atmospheric and Oceanic Physics', '大気海洋物理学'],
 ['physics.app-ph', 'Applied Physics', '応用物理学'],
 ['physics.atm-clus', 'Atomic and Molecular Clusters', '原子・分子クラスター'],
 ['physics.atom-ph', 'Atomic Physics', '原子物理学'],
 ['physics.bio-ph', 'Biological Physics', '生物物理学'],
 ['physics.chem-ph', 'Chemical Physics', '化学物理学'],
 ['physics.class-ph', 'Classical Physics', '古典物理学'],
 ['physics.comp-ph', 'Computational Physics', '計算物理学'],
 ['physics.data-an',
  'Data Analysis, Statistics and Probability',
  'データ分析・統計・確率'],
 ['physics.ed-ph', 'Physics Education', '物理学教育'],
 ['physics.flu-dyn', 'Fluid Dynamics', '流体力学'],
 ['physics.gen-ph', 'General Physics', '物理学一般'],
 ['physics.geo-ph', 'Geophysics', '地球物理学'],
 ['physics.hist-ph', 'History and Philosophy of Physics', '物理学の歴史と哲学'],
 ['physics.ins-det', 'Instrumentation and Detectors', '計装・検出器'],
 ['physics.med-ph', 'Medical Physics', '医学物理学'],
 ['physics.optics', 'Optics', '光学系'],
 ['physics.plasm-ph', 'Plasma Physics', 'プラズマ物理学'],
 ['physics.pop-ph', 'Popular Physics', '人気の物理学'],
 ['physics.soc-ph', 'Physics and Society', '物理学と社会'],
 ['physics.space-ph', 'Space Physics', '宇宙物理学'],
 ['q-bio.BM', 'Biomolecules', '生体分子'],
 ['q-bio.CB', 'Cell Behavior', '細胞行動'],
 ['q-bio.GN', 'Genomics', 'ゲノミクス'],
 ['q-bio.MN', 'Molecular Networks', '分子ネットワーク'],
 ['q-bio.NC', 'Neurons and Cognition', '神経細胞と認知'],
 ['q-bio.OT', 'Other Quantitative Biology', 'その他の定量生物学'],
 ['q-bio.PE', 'Populations and Evolution', '集団と進化'],
 ['q-bio.QM', 'Quantitative Methods', '定量的な方法'],
 ['q-bio.SC', 'Subcellular Processes', '細胞内プロセス'],
 ['q-bio.TO', 'Tissues and Organs', '組織と臓器'],
 ['q-fin.CP', 'Computational Finance', '計算ファイナンス'],
 ['q-fin.EC', 'Economics', '経済学'],
 ['q-fin.GN', 'General Finance', '財務全般'],
 ['q-fin.MF', 'Mathematical Finance', '数理ファイナンス'],
 ['q-fin.PM', 'Portfolio Management', 'ポートフォリオ管理'],
 ['q-fin.PR', 'Pricing of Securities', '有価証券の価格設定'],
 ['q-fin.RM', 'Risk Management', 'リスク管理'],
 ['q-fin.ST', 'Statistical Finance', '統計的金融'],
 ['q-fin.TR', 'Trading and Market Microstructure', '取引と市場のミクロ構造'],
 ['quant-ph', 'Quantum Physics', '量子物理学'],
 ['stat.AP', 'Applications', 'アプリケーション'],
 ['stat.CO', 'Computation', '計算'],
 ['stat.ME', 'Methodology', '方法論'],
 ['stat.ML', 'Machine Learning', '機械学習'],
 ['stat.OT', 'Other Statistics', 'その他の統計'],
 ['stat.TH', 'Statistics Theory', '統計理論']]